function [fitresult, gof] = createFit(N, policy, plotme)
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%  Auto-generated by MATLAB on 21-Oct-2018 12:59:33

%% Fit
[xData, yData] = prepareCurveData(1:length(policy), policy);

% Set up fittype and options.


str = sprintf('min((1/%d)*exp(a^x), 0.5)', N);
% str = sprintf('min((1/%d)*a^x, 1)', N);
ft = fittype( str, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.997369045818215;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if plotme
    % Plot fit with data.
    figure( 'Name', 'Approximation min((1/N)*e^(alpha*t)))');
    h = plot( fitresult, xData, yData );
    legend( h, 'policy', 'approximation', 'Location', 'NorthEast' );
    % Label axes
    ylabel probabilities
    grid on
end
